import type { Metadata } from "next";
import { DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pomdoro todo",
  description: "Generated by create next app",
};

const dmsans = DM_Sans({ subsets: ["latin"] });
const dmmono = DM_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dmmono",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${dmsans.className} ${dmmono.variable} mx-auto max-w-4xl py-12 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
